# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Install Dependencies
          command: npm install -g vuepress gh-pages
      - run:
          name: Build Site
          command: npm run docs:build
      - run:
          name: Deploy docs
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/.vuepress/dist
