# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
workflows:
  version: 2
  jobs:
    - docs-build
    - docs-deploy:
        requires:
          - docs-build
        filters:
          branches:
            only: master2
docs-build:
  docker:
    - image: python:3.7
  steps:
    - checkout
    - run:
        name: Install Dependencies
        command: npm install vuepress
    - run:
        name: Build Docs
        command: npm run docs:build
    - persist_to_workspace:
        root: docs/.vuepress
        paths: dist
docs-deploy:
  docker:
    - image: node:8.10.0
  steps:
    - checkout
    - run:
        name: Install and configure dependencies
        command: |
          npm install -g --silent gh-pages
    - run:
        name: Deploy docs to gh-pages branch
        command: gh-pages --dist docs/.vuepress/dist
